#spring.application.name=property-access-client-2
#
#
#management.endpoints.web.exposure.include=*
#spring.cloud.config.server.git.default-label=main
#spring.config.import=optional:configserver:http://localhost:9090
server:
  port: 9090
  
spring:
  config:
    import:
    - optional:configserver:http://localhost:8888
  application:
    name: db1
  profiles:
    active:
    - default
  cloud:
    config:
      uri:
      - http://localhost:8888